# Generated by Django 2.0.6 on 2018-09-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contesttype', models.CharField(max_length=3)),
                ('ContestCode', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField()),
            ],
            options={
                'ordering': ['-startDate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='pendingrequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userp', models.CharField(default='abcds', max_length=100)),
                ('teamidp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemcode', models.CharField(help_text='Enter problem codes', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100)),
                ('teamid', models.CharField(default='ab', max_length=100)),
                ('user1', models.CharField(blank=True, max_length=100, null=True)),
                ('user2', models.CharField(blank=True, max_length=100, null=True)),
                ('user3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='abc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContestCode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ContestSpace.Team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ContestSpace.User')),
            ],
            options={
                'ordering': ['-startDate'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problemcode',
            field=models.ManyToManyField(help_text='Select Problems', to='ContestSpace.Problem'),
        ),
    ]
