# Generated by Django 2.0.6 on 2018-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestSpace', '0002_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='teamname',
            field=models.CharField(default='ab', max_length=100),
        ),
    ]
