# Generated by Django 2.0.6 on 2018-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestSpace', '0003_pendingrequests_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontest',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
